# Generated by Django 2.2.24 on 2023-02-19 10:07

from django.db import migrations


def autocomplete_new_buildings_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_buildings = Flat.objects.filter(construction_year__gte="2015")
    for new_building in new_buildings:
        new_building.new_building = True
        new_building.save()
    old_buildings = Flat.objects.filter(construction_year__lt="2015")
    for old_building in old_buildings:
        old_building.new_building = False
        old_building.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230219_1304'),
    ]

    operations = [
        migrations.RunPython(autocomplete_new_buildings_field),
    ]
