# Generated by Django 2.2.24 on 2023-02-19 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='users_liked',
            field=models.ManyToManyField(related_name='flats_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
