# Generated by Django 2.2.24 on 2023-02-19 12:25

from django.db import migrations
from phonenumbers import parse


def automake_pure_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_pure_phone = parse(flat.owners_phonenumber, "RU")
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owners_pure_phone'),
    ]

    operations = [
        migrations.RunPython(automake_pure_phone_numbers),
    ]
