# Generated by Django 2.2.24 on 2023-02-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230219_1534'),
    ]

    operations = [
    ]
