# Generated by Django 2.2.24 on 2023-02-19 12:55

from django.db import migrations
import phonenumbers
from django.db.models import F


def get_phone_pure_number(owners_phonenumber):
    owners_pure_phone = phonenumbers.parse(owners_phonenumber, "RU")
    if phonenumbers.is_valid_number(owners_pure_phone):
        return owners_pure_phone
    else:
        return None


def automake_pure_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owners_pure_phone=get_phone_pure_number(F('owners_phonenumber')))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230219_1549'),
    ]

    operations = [
        migrations.RunPython(automake_pure_phone_numbers),
    ]
