# Generated by Django 2.2.24 on 2023-02-19 12:55

from django.db import migrations
import phonenumbers


def automake_pure_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(flat.owners_pure_phone):
            flat.save()
        else:
            flat.owners_pure_phone = None
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230219_1549'),
    ]

    operations = [
        migrations.RunPython(automake_pure_phone_numbers),
    ]
