# Generated by Django 2.2.24 on 2023-02-19 13:51

from django.db import migrations


def autocomplete_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_pure_phone=flat.owners_pure_phone,
        )
        owner.save()
        owner.flats.add(flat)
        owner.save()
        flat.save()
        flat.owners.add(owner)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20230219_1612'),
    ]

    operations = [
        migrations.RunPython(autocomplete_owners),
    ]
