# Generated by Django 2.2.24 on 2023-02-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20230219_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_pure_phone',
        ),
    ]
