# Generated by Django 2.2.24 on 2023-02-20 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0020_auto_20230220_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
