# Generated by Django 2.2.24 on 2023-03-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_auto_20230310_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_pure_phone',
        ),
    ]
